#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ $local_branch =~ "master" ]]
then
	exit 0
fi

valid_branch_regex="^(feat|fix|chore|refactor|style|test|perf|docs|ci|build)\/[A-Z]+-[0-9]+\/.+$"

message="Branch name $local_branch is invalid!
Needs to follow the naming scheme [feature type]/[jira ticket]/[descriotion].

Example: fix/ABC-123/fixed-crash-when-booting

In emergencies you can use NOTICKET as the ticket id to bypass this check."

if [[ $local_branch == *"NOTICKET"* ]]; then
  exit 0
fi

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
