# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # Updates the default branch for this repository.
  default_branch: master
  
  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false` to prevent merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging.
  allow_rebase_merge: false

  # The commit title and body for squash merge commits.
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY

# Collaborators: give specific users access to this repository.
collaborators:
  # The username of the collaborator and their permission level
  - username: developers
    permission: maintain

branches:
  - name: master
    # Branch Protection settings. Set to null to disable
    protection: null
